### PR TITLE
LPS-61258

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hey Tom,

can you run this with the login grinder?  Thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
hey preston, do you still want me to test these two that you closed?

On Fri, Jan 8, 2016 at 5:43 PM, Nathaniel Preston Crary <
notifications@github.com> wrote:

> Closed #28 https://github.com/tomwang2011/liferay-portal/pull/28.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomwang2011/liferay-portal/pull/28#event-510061560.

## 

Best Regards,

Tom Wang

**Comment by Preston-Crary** [comment]
Hmm, I thought you did test them.  Yes please test this one.

**Comment by tomwang2011** [comment]
okay I tested the pulls end in 64 and 69, not the two after, I saw them
being closed so i didn't know whether to test. I'll run those 2 today, will
they work on today's master?

On Sun, Jan 10, 2016 at 11:08 PM, Nathaniel Preston Crary <
notifications@github.com> wrote:

> Hmm, I thought you did test them. Yes please test this one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tomwang2011/liferay-portal/pull/28#issuecomment-170451080
> .

## 

Best Regards,

Tom Wang

**Comment by Preston-Crary** [comment]
Yes, it should work.

**Pull request closed without merging**
