### PR TITLE
LPS-78050

### PR DESCRIPTION
**Pull request by petershin**
Hi Tom, does https://github.com/tomwang2011/liferay-portal/pull/473/commits/23f617b72eeb3e275cc56a7109a47da4ebb35e44 look ok to you?

@hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by tomwang2011** [comment]
@petershin yes that is correct, their dependency will be broken if they update the version of their dependency on blogs.item.selector.web as the new version of it no longer exports that package, thanks!

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
Appreciate it!  Sent the fix to Brian: https://github.com/brianchandotcom/liferay-portal/pull/55944

**Pull request closed without merging**
