### PR TITLE
LPS-74610 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-74610

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test

**Comment by brianwulbern** [comment]
@tomwang2011, I haven't triggered the proxy-affected tests to run as acceptance in this pull, I can add that on so we can get some results on it today.  It looks like there are some SocksProxy unit tests that need to be fixed/dealt with, too.

cc @michaelhashimoto

**Comment by brianwulbern** [comment]
ci:retest

**Comment by tomwang2011** [comment]
@brianwulbern, please ignore the modules-unit failures on the proxy for now, I am working on them, it seems the test isn't playing well with CI environment.

**Comment by brianwulbern** [comment]
@tomwang2011 @michaelhashimoto 

* I think we'll need to add `smtp.gmail.com` to all the gmail-related tests, as it can load gmail, but no mail is sent.
* xuggler related tests might need access to `files.liferay.com` according to Austin's comment [here](https://issues.liferay.com/browse/LRQA-36127?focusedCommentId=1206093&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1206093)
* According to the log on the twitter test, we might need the private https?:
```
 23:16:24,860 INFO  [liferay/scheduler_dispatch-4][RetryExec:159] I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.twitter.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
     [exec] 23:16:24,868 INFO  [liferay/scheduler_dispatch-4][RetryExec:159] Retrying request to {s}->https://www.twitter.com:443
```
* Login#OpenSSOSmoke [Jenkins log](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/174868/AXIS_VARIABLE=0,label_exp=!master/consoleFull)
```
 [exec]     ###
     [exec]     ### Login#OpenSSOSmoke
     [exec]     ###
     [exec] 
     [exec]     Buildfile: /opt/dev/projects/github/liferay-portal/build-test-authentication.xml
     [exec] 
     [exec]     run-openam-tools:
     [exec]          [java] Checking license acceptance...License terms accepted.
     [exec]          [java] Checking configuration directory /root/openam....Success.
     [exec]          [java] Installing OpenAM configuration store...Success RSA/ECB/OAEPWithSHA1AndMGF1Padding.
     [exec]          [java] Extracting OpenDJ, please wait...Complete
     [exec]          [java] Running OpenDJ setupSetup command: --cli --adminConnectorPort 4444 --baseDN dc=openam,dc=forgerock,dc=org --rootUserDN cn=Directory Manager --ldapPort 50389 --skipPortCheck --rootUserPassword xxxxxxx --jmxPort 1689 --no-prompt --doNotStart --hostname test.able.com %0ASee+%2Fopt%2Fdev%2Fprojects%2Fgithub%2Fliferay-portal%2Fbundles%2Ftomcat-8.0.32%2Ftemp%2Fopendj-setup-1515461521756780472.log+for+a+detailed+log+of+this+operation.%0A%0AConfiguring+Directory+Server+.....+Done.%0A%0ATo+see+basic+server+configuration+status+and+configuration+you+can+launch+%2Froot%2Fopenam%2Fopends%2Fbin%2Fstatus%0A...Success.
     [exec]          [java] ...Success
     [exec]          [java] Installing OpenAM configuration store in /root/openam/opends...Success.
     [exec] com.sun.identity.setup.ConfiguratorException: emb.creatingfamsuffix.failure, refer to install.log under /root/openam for more information.
     [exec] 	at com.sun.identity.setup.AMSetupServlet.processRequest(AMSetupServlet.java:802)
```
* Login#facebookSSOSmoke needs `graph.facebook.com`
* OSGiCurrencyconverter#ConvertCurrencyUSDToEUR needs `http://finance.yahoo.com`
* [Login#GoogleSSOSmoke](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/209277/AXIS_VARIABLE=0,label_exp=!master/consoleFull)
```
 [exec]     ###
     [exec]     ### Login#GoogleSSOSmoke
     [exec]     ###
     [exec] 
     [exec]     Checking to see if TCat is enabled...
     [exec]     Log out of Liferay Portal.
     [exec] 08-Jan-2018 23:14:32.685 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Main Servlet] in context with path [] threw exception
     [exec]  java.net.SocketException: Can't connect to SOCKS proxy:Connection refused (Connection refused)
     [exec] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
```
* [Login#OpenIDSmoke](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/192698/AXIS_VARIABLE=0,label_exp=!master/consoleFull)
```
  [exec]     ###
     [exec]     ### Login#OpenIDSmoke
     [exec]     ###
     [exec] 
     [exec]     Checking to see if TCat is enabled...
     [exec]     Log out of Liferay Portal.
     [exec]     Log into Liferay Portal as userea2@liferay.com using the password test with OpenID authentication enabled.
     [exec] 23:13:59,859 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] I/O exception (java.net.SocketException) caught when connecting to the target host: Can't connect to SOCKS proxy:Connection refused (Connection refused)
     [exec] 23:13:59,860 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] Retrying connect
     [exec] 23:13:59,861 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] I/O exception (java.net.SocketException) caught when connecting to the target host: Can't connect to SOCKS proxy:Connection refused (Connection refused)
     [exec] 23:13:59,861 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] Retrying connect
     [exec] 23:13:59,862 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] I/O exception (java.net.SocketException) caught when connecting to the target host: Can't connect to SOCKS proxy:Connection refused (Connection refused)
     [exec] 23:13:59,862 INFO  [http-nio-8080-exec-3][DefaultHttpClient:159] Retrying connect
     [exec] 
```
* BlogsUsecase#DemoTrackbackURL maybe it needs the full: `http://www.able.com:8080`?
* All Xuggler tests:
```
  [exec] 
     [exec]     ###
     [exec]     ### WebcontentUsecase#AddAudioViaWebContent
     [exec]     ###
     [exec] 
     [exec]     Checking to see if TCat is enabled...
     [exec] 23:14:42,884 ERROR [http-nio-8080-exec-1][XugglerImpl:134] Liferay does not have the Xuggler native libraries installed. In order to generate video and audio previews, please follow the instructions for Xuggler in the Server Administration section of the Control Panel at: http://<server>/group/control_panel/manage/-/server/external-services. Error message is: no xuggle in java.library.path
     [exec]     LIFERAY_ERROR: Liferay does not have the Xuggler native libraries installed. In order to generate video and audio previews, please follow the instructions for Xuggler in the Server Administration section of the Control Panel at: http://<server>/group/control_panel/manage/-/server/external-services. Error message is: no xuggle in java.library.path
     [exec] 
```

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@tomwang2011 @michaelhashimoto, it looks like my updated hosts didn't change the test outcome.

They're basically the same results we see for these tests on [7.0.x-private](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&tabs1=all-cases&testrayRunId=146436947&statuses=4%2C3%2C1%2C2%2C7%2C0)

**Comment by brianwulbern** [comment]
@tomwang2011, I don't think I was able to block the outside network with the tomcat configuration you suggested.  I ran the RSS test locally and had no issues, so I'm not sure where to go from here.  Would appreciate your help to resolve the remaining proxy failures above, as I'll be heading back to the CN office this weekend.  Thanks!

cc @michaelhashimoto

**Comment by brianwulbern** [comment]
Testing on 7.0.x over here: https://github.com/michaelhashimoto/liferay-portal-ee/pull/2038

**Pull request closed without merging**
