### PR TITLE
Wiki service upgrade

### PR DESCRIPTION
**Pull request by Preston-Crary**
@tomwang2011, please run this against the wiki grinder test case, thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
@tomwang2011, all tests should be green now. Please go ahead with running the test.

Thanks for waiting for me to fix the failures.

**Comment by tomwang2011** [comment]
Hey @Preston-Crary I didn't see much difference in results for this pull, the results are at: smb://172.16.0.30/benchmark/2016/TestPulls-Preston/06-15-17-wiki-wikiserviceupgrade, I am running a sampling profile right now and i'll put that in after its done.

**Pull request closed without merging**
